### ISSUE TITLE
Error in Protein Sequences tab: Error in curl::curl_fetch_memory: Timeout was reached

### ISSUE THREAD

**Issue by buithuytien** [buithuytien/ABioTrans#45]
Error message on Sequence charge:

Listening on http://127.0.0.1:7565
[1] "P61981" "P62258" "P31947" "E9Q397" "Q9CQV8" "Q04917" "Q64514"
Internet connection problem occurs and the function will return the original error
Warning: Error in curl::curl_fetch_memory: Timeout was reached: [www.uniprot.org] Operation timed out after 4033 milliseconds with 0 out of 0 bytes received
  182: <Anonymous>

![image](https://user-images.githubusercontent.com/47216718/97853099-9d538980-1d32-11eb-9f9b-57d2949fc79c.png)

**Comment by buithuytien** [comment]
resolved

**Comment by menanashat** [comment]
how did you solve it
